squashing a bunch of commits
begin add changes for blake
handle message if config file isn't present
clean up arghandling. prepare for crust. this code needs checked.
closer for beta testing readiness
TypeError: cannot use a string pattern on a byteslike object
add update manuf option
oui_update
Update CODE_OF_CONDUCT.md
replace subprocess with python code
add parent process ids
fpms
pymongo db support
Create CAPABILITY_LOGIC.md
flake8 config moved to tox.ini